name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list file
        run: ls

      - name: Print Name
        run: echo "Vrinda"

  say-bye:
    runs-on: ubuntu-latest  
    needs: say-hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Check Node version
        run: node -v 
        
      - name: Check Node version
        run: node -v 
        

      - name: starting test
        run: npm run test 

      - name: Print Goodbye
        run: echo "Goodbye from second job"
