name: My First Workflow

on: push

jobs:
say-hello:
runs-on: ubuntu-latest


steps:
  - name: Print message
    run: echo "Hello, GitHub Actions!"
  - name: Print Name
    run: echo "vrinda"


say-bye:
runs-on: ubuntu-latest

steps:
  - name: Print goodbye message
    run: echo "Goodbye from second job"


